defaults:
- repro_singleseq_wce_base.yaml
- repro_feat_extractor_transformer.yaml
- _self_
model_factory_ImplicitronModelFactory_args:
  model_GenericModel_args:
    chunk_size_grid: 16000
    view_pooler_enabled: true
    implicit_function_class_type: NeRFormerImplicitFunction
    raysampler_AdaptiveRaySampler_args:
      n_rays_per_image_sampled_from_mask: 800
      n_pts_per_ray_training: 32
      n_pts_per_ray_evaluation: 32
    renderer_MultiPassEmissionAbsorptionRenderer_args:
      n_pts_per_ray_fine_training: 16
      n_pts_per_ray_fine_evaluation: 16
    view_pooler_args:
      feature_aggregator_class_type: IdentityFeatureAggregator
