model_factory_ImplicitronModelFactory_args:
  model_GenericModel_args:
    image_feature_extractor_class_type: ResNetFeatureExtractor
    image_feature_extractor_ResNetFeatureExtractor_args:
      add_images: true
      add_masks: true
      first_max_pool: false
      image_rescale: 0.375
      l2_norm: true
      name: resnet34
      normalize_image: true
      pretrained: true
      stages:
      - 1
      - 2
      - 3
      - 4
      proj_dim: 16
