defaults:
- repro_multiseq_base.yaml
- _self_
model_factory_ImplicitronModelFactory_args:
  model_GenericModel_args:
    chunk_size_grid: 16000
    view_pooler_enabled: false
    n_train_target_views: -1
    num_passes: 1
    loss_weights:
      loss_rgb_mse: 200.0
      loss_prev_stage_rgb_mse: 0.0
      loss_mask_bce: 1.0
      loss_prev_stage_mask_bce: 0.0
      loss_autodecoder_norm: 0.001
      depth_neg_penalty: 10000.0
    global_encoder_class_type: SequenceAutodecoder
    global_encoder_SequenceAutodecoder_args:
      autodecoder_args:
        encoding_dim: 256
        n_instances: 20000
    raysampler_class_type: NearFarRaySampler
    raysampler_NearFarRaySampler_args:
      n_rays_per_image_sampled_from_mask: 2048
      min_depth: 0.05
      max_depth: 0.05
      n_pts_per_ray_training: 1
      n_pts_per_ray_evaluation: 1
      stratified_point_sampling_training: false
      stratified_point_sampling_evaluation: false
    renderer_class_type: LSTMRenderer
    implicit_function_class_type: SRNHyperNetImplicitFunction
optimizer_factory_ImplicitronOptimizerFactory_args:
  breed: Adam
  lr: 5.0e-05
