generic_model_args:
  image_feature_extractor_args:
    add_images: true
    add_masks: true
    first_max_pool: true
    image_rescale: 0.375
    l2_norm: true
    name: resnet34
    normalize_image: true
    pretrained: true
    stages:
    - 1
    - 2
    - 3
    - 4
    proj_dim: 32
